function Plot_increaseC(xvector1, yvector1)
%CREATEFIGURE(XVECTOR1, YVECTOR1)
%  XVECTOR1:  bar xvector
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 12-Mar-2018 17:55:22

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create bar
bar(xvector1,yvector1,'LineStyle','none');

% Create xlabel
xlabel({'Arc'});

% Create ylabel
ylabel({'OF'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 31.2368073878628]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[2581.51391297758 2635.41865494481]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XGrid','on','XTick',...
    [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30],...
    'YGrid','on');
